<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // DB::table('brands')->insert([
      //       ['ACER' => 'ACER'],
      //       ['ALCATEL' => 'ALCATEL'],
      //       ['ALLVIEW' => 'ALLVIEW'],
      //       ['AMOI' => 'AMOI'],
      //       ['APPLE' => 'APPLE'],
      //       ['ARCHOS' => 'ARCHOS'],
      //       ['ASUS' => 'ASUS'],
      //       ['AT&T' => 'AT&T'],
      //       ['BENEFON' => 'BENEFON'],
      //       ['BENQ' => 'BENQ'],
      //       ['BENQ-SIEMENS' => 'BENQ-SIEMENS'],
      //       ['BIRD' => 'BIRD'],
      //       ['BLACKBERRY' => 'BLACKBERRY'],
      //       ['BLACKVIEW' => 'BLACKVIEW'],
      //       ['BLU' => 'BLU'],
      //       ['BOSCH' => 'BOSCH'],
      //       ['BQ' => 'BQ'],
      //       ['CASIO' => 'CASIO'],
      //       ['CAT' => 'CAT'],
      //       ['CELKON' => 'CELKON'],
      //       ['CHEA' => 'CHEA'],
      //       ['COOLPAD' => 'COOLPAD'],
      //       ['CUBOT' => 'CUBOT'],
      //       ['DELL' => 'DELL'],
      //       ['DOOGEE' => 'DOOGEE'],
      //       ['EMPORIA' => 'EMPORIA'],
      //       ['ENERGIZER' => 'ENERGIZER'],
      //       ['ERICSSON' => 'ERICSSON'],
      //       ['ETEN' => 'ETEN'],
      //       ['FAIRPHONE' => 'FAIRPHONE'],
      //       ['FUJITSU SIEMENS' => 'FUJITSU SIEMENS'],
      //       ['GARMIN-ASUS' => 'GARMIN-ASUS'],
      //       ['GIGABYTE' => 'GIGABYTE'],
      //       ['GIONEE' => 'GIONEE'],
      //       ['GOOGLE' => 'GOOGLE'],
      //       ['HAIER' => 'HAIER'],
      //       ['HMD' => 'HMD'],
      //       ['HONOR' => 'HONOR'],
      //       ['HP' => 'HP'],
      //       ['HTC' => 'HTC'],
      //       ['HUAWEI' => 'HUAWEI'],
      //       ['I-MATE' => 'I-MATE'],
      //       ['I-MOBILE' => 'I-MOBILE'],
      //       ['ICEMOBILE' => 'ICEMOBILE'],
      //       ['INFINIX' => 'INFINIX'],
      //       ['INNOSTREAM' => 'INNOSTREAM'],
      //       ['INQ' => 'INQ'],
      //       ['INTEX' => 'INTEX'],
      //       ['ITEL' => 'ITEL'],
      //       ['JOLLA' => 'JOLLA'],
      //       ['KARBONN' => 'KARBONN'],
      //       ['KYOCERA' => 'KYOCERA'],
      //       ['LAVA' => 'LAVA'],
      //       ['LEECO' => 'LEECO'],
      //       ['LENOVO' => 'LENOVO'],
      //       ['LG' => 'LG'],
      //       ['MAXON' => 'MAXON'],
      //       ['MAXWEST' => 'MAXWEST'],
      //       ['MEIZU' => 'MEIZU'],
      //       ['MICROMAX' => 'MICROMAX'],
      //       ['MICROSOFT' => 'MICROSOFT'],
      //       ['MITAC' => 'MITAC'],
      //       ['MITSUBISHI' => 'MITSUBISHI'],
      //       ['MODU' => 'MODU'],
      //       ['MOTOROAL' => 'MOTOROAL'],
      //       ['MWG' => 'MWG'],
      //       ['NEC' => 'NEC'],
      //       ['NEONODE' => 'NEONODE'],
      //       ['NIU' => 'NIU'],
      //       ['NOKIA' => 'NOKIA'],
      //       ['NOTHING' => 'NOTHING'],
      //       ['NVIDIA' => 'NVIDIA'],
      //       ['O2' => 'O2'],
      //       ['ONEPLUS' => 'ONEPLUS'],
      //       ['OPPO' => 'OPPO'],
      //       ['ORANGE' => 'ORANGE'],
      //       ['OSCAL' => 'OSCAL'],
      //       ['OUKITEL' => 'OUKITEL'],
      //       ['PALM' => 'PALM'],
      //       ['PANASONIC' => 'PANASONIC'],
      //       ['PANTECH' => 'PANTECH'],
      //       ['PARLA' => 'PARLA'],
      //       ['PHILIPS' => 'PHILIPS'],
      //       ['PLUM' => 'PLUM'],
      //       ['POSH' => 'POSH'],
      //       ['PRESTIGIO' => 'PRESTIGIO'],
      //       ['QMOBILE' => 'QMOBILE'],
      //       ['QTEK' => 'QTEK'],
      //       ['RAZER' => 'RAZER'],
      //       ['REALME' => 'REALME'],
      //       ['SAGEM' => 'SAGEM'],
      //       ['SAMSUNG' => 'SAMSUNG'],
      //       ['SENDO' => 'SENDO'],
      //       ['SEWON' => 'SEWON'],
      //       ['SHAPE' => 'SHAPE'],
      //       ['SIEMENS' => 'SIEMENS'],
      //       ['SONIM' => 'SONIM'],
      //       ['SONY' => 'SONY'],
      //       ['SONY ERICSSON' => 'SONY ERICSSON'],
      //       ['SPICE' => 'SPICE'],
      //       ['T-MOBILE' => 'T-MOBILE'],
      //       ['TCL' => 'TCL'],
      //       ['TECNO' => 'TECNO'],
      //       ['TEL.ME.' => 'TEL.ME.'],
      //       ['TELIT' => 'TELIT'],
      //       ['TELIT' => 'TELIT'],
      //       ['THURAYA' => 'THURAYA'],
      //       ['TOSHIBA' => 'TOSHIBA'],
      //       ['ULEFONE' => 'ULEFONE'],
      //       ['UMIDIGI' => 'UMIDIGI'],
      //       ['UNNECTO' => 'UNNECTO'],
      //       ['VERTU' => 'VERTU'],
      //       ['VERYKOOL' => 'VERYKOOL'],
      //       ['VIVO' => 'VIVO'],
      //       ['VK MOBILE' => 'VK MOBILE'],
      //       ['VODAFONE' => 'VODAFONE'],
      //       ['WIKO' => 'WIKO'],
      //       ['WND' => 'WND'],
      //       ['XCUTE' => 'XCUTE'],
      //       ['XIAMOI' => 'XIAMOI'],
      //       ['XOLO' => 'XOLO'],
      //       ['YEZZ' => 'YEZZ'],
      //       ['YOTA' => 'YOTA'],
      //       ['YU' => 'YU'],
      //       ['ZTE' => 'ZTE'],
      //   ]);
    }
}
